package org.sample.com.model;
// Generated Jun 16, 2018 11:48:50 AM by Hibernate Tools 5.2.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="sample"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class City  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private String name;
     private Set<Company> companies = new HashSet<Company>(0);
     private Set<Location> locations = new HashSet<Location>(0);
     private Set<Locality> localities = new HashSet<Locality>(0);

    public City() {
    }

	
    public City(String name) {
        this.name = name;
    }
    public City(String name, Set<Company> companies, Set<Location> locations, Set<Locality> localities) {
       this.name = name;
       this.companies = companies;
       this.locations = locations;
       this.localities = localities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Company> getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set<Company> companies) {
        this.companies = companies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Location> getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set<Location> locations) {
        this.locations = locations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Locality> getLocalities() {
        return this.localities;
    }
    
    public void setLocalities(Set<Locality> localities) {
        this.localities = localities;
    }




}


