package org.sample.com.model;
// Generated Jun 16, 2018 11:48:50 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "sample", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class City implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private List<Company> companies = new ArrayList<Company>(0);
	private List<Location> locations = new ArrayList<Location>(0);
	private List<Locality> localities = new ArrayList<Locality>(0);

	public City() {
	}

	public City(String name) {
		this.name = name;
	}

	public City(String name, List<Company> companies, List<Location> locations, List<Locality> localities) {
		this.name = name;
		this.companies = companies;
		this.locations = locations;
		this.localities = localities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH}, mappedBy = "city")
	public List<Company> getCompanies(){
	      return this.companies;
	}

	public void setCompanies(List<Company> companies) {
		this.companies = companies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public List<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(List<Location> locations) {
		this.locations = locations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public List<Locality> getLocalities() {
		return this.localities;
	}

	public void setLocalities(List<Locality> localities) {
		this.localities = localities;
	}

}
