package org.sample.com.model;
// Generated Mar 19, 2018 3:20:26 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Employee generated by hbm2java
 */

@SqlResultSetMappings({ @SqlResultSetMapping(name = "employee_details", classes = {
		@ConstructorResult(targetClass = Employee.class, columns = { @ColumnResult(name = "id"),
				@ColumnResult(name = "firstName"), @ColumnResult(name = "empName"), @ColumnResult(name = "joinDate"),
				@ColumnResult(name = "salary"), @ColumnResult(name = "emailId"), @ColumnResult(name = "status"),
				@ColumnResult(name = "cityName"), @ColumnResult(name = "companyName"), @ColumnResult(name = "desig"),
				@ColumnResult(name = "exp"), @ColumnResult(name = "mobileNo") }) }),
		@SqlResultSetMapping(name = "employee_view", classes = {
				@ConstructorResult(targetClass = EmployeeDetails.class, columns = { @ColumnResult(name = "id"),
						@ColumnResult(name = "firstName"), @ColumnResult(name = "empName"),
						@ColumnResult(name = "joinDate"), @ColumnResult(name = "salary"),
						@ColumnResult(name = "emailId"), @ColumnResult(name = "status"),
						@ColumnResult(name = "cityName"), @ColumnResult(name = "companyName"),
						@ColumnResult(name = "desig"), @ColumnResult(name = "exp"), @ColumnResult(name = "mobileNo") }) }) })

@Entity
@Table(name = "employee", catalog = "sample", uniqueConstraints = { @UniqueConstraint(columnNames = "emailId"),
		@UniqueConstraint(columnNames = "mobileNo"), @UniqueConstraint(columnNames = "empName") })
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private City city;
	private Company company;
	private String firstName;
	private String empName;
	private Date joinDate;
	private double salary;
	private String emailId;
	private int status;
	private String desig;
	private int exp;
	private String companyName;
	private String cityName;
	private String mobileNo;

	public Employee() {
	}

	public Employee(City city, Company company, String firstName, String empName, Date joinDate, double salary,
			String emailId, int status, String desig, int exp, String mobileNo) {
		this.city = city;
		this.company = company;
		this.firstName = firstName;
		this.empName = empName;
		this.joinDate = joinDate;
		this.salary = salary;
		this.emailId = emailId;
		this.status = status;
		this.desig = desig;
		this.exp = exp;
		this.mobileNo = mobileNo;
	}

	public Employee(int id, String firstName, String empName, Date joinDate, double salary, String emailId, int status,
			String cityName, String companyName, String desig, Integer exp, String mobileNo) {
		this.id = id;
		this.firstName = firstName;
		this.empName = empName;
		this.joinDate = joinDate;
		this.salary = salary;
		this.emailId = emailId;
		this.status = status;
		this.cityName = cityName;
		this.companyName = companyName;
		this.desig = desig;
		this.exp = exp;
		this.mobileNo = mobileNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cityName", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "companyName", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "firstName", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "empName", unique = true, nullable = false, length = 45)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "joinDate", nullable = false, length = 10)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Column(name = "salary", nullable = false, precision = 22, scale = 0)
	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	@Column(name = "emailId", unique = true, nullable = false, length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "desig", nullable = false, length = 45)
	public String getDesig() {
		return this.desig;
	}

	public void setDesig(String desig) {
		this.desig = desig;
	}

	@Column(name = "exp", nullable = false)
	public int getExp() {
		return this.exp;
	}

	public void setExp(int exp) {
		this.exp = exp;
	}

	@Transient
	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Transient
	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "mobileNo", unique = true, nullable = false, length = 45)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}
}
