package org.sample.com.model;
// Generated Mar 19, 2018 3:20:26 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Employee generated by hbm2java
 */

public class EmployeeDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String firstName;
	private String lastName;
	private String empName;
	private String emailId;
	private String companyName;
	private String gender;
	private Date dob;
	private int age;
	private String mobileNo;
	private String address;
	private String cityName;
	private String country;
	private String pincode;
	private double salary;
	private Date joinDate;
	private String desig;
	private int exp;
	private boolean status;

	public EmployeeDetails() {
	}

	public EmployeeDetails(int id, String firstName, String lastName, String empName, String emailId,
			String companyName, String gender, Date dob, int age, String mobileNo, String address, String cityName,
			String country, String pincode, double salary, Date joinDate, String desig, int exp, boolean status) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.empName = empName;
		this.emailId = emailId;
		this.companyName = companyName;
		this.gender = gender;
		this.dob = dob;
		this.age = age;
		this.mobileNo = mobileNo;
		this.address = address;
		this.cityName = cityName;
		this.country = country;
		this.pincode = pincode;
		this.salary = salary;
		this.joinDate = joinDate;
		this.desig = desig;
		this.exp = exp;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Temporal(TemporalType.DATE)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public boolean isStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getDesig() {
		return this.desig;
	}

	public void setDesig(String desig) {
		this.desig = desig;
	}

	public int getExp() {
		return this.exp;
	}

	public void setExp(int exp) {
		this.exp = exp;
	}
	
	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPincode() {
		return pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

}
