package org.sample.com.model;

//Generated Mar 19, 2018 3:20:26 PM by Hibernate Tools 5.2.1.Final
/**
* Employee generated by hbm2java
*/

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

@SqlResultSetMappings({ @SqlResultSetMapping(name = "employee_details", classes = {
		@ConstructorResult(targetClass = Employee.class, columns = { @ColumnResult(name = "id"),
				@ColumnResult(name = "firstName"), @ColumnResult(name = "empName"), @ColumnResult(name = "joinDate"),
				@ColumnResult(name = "salary"), @ColumnResult(name = "emailId"), @ColumnResult(name = "status"),
				@ColumnResult(name = "cityName"), @ColumnResult(name = "companyName"), @ColumnResult(name = "desig"),
				@ColumnResult(name = "exp"), @ColumnResult(name = "mobileNo") }) }),
		@SqlResultSetMapping(name = "employee_view", classes = {
				@ConstructorResult(targetClass = EmployeeDetails.class, columns = { @ColumnResult(name = "id"),
						@ColumnResult(name = "firstName"), @ColumnResult(name = "empName"),
						@ColumnResult(name = "joinDate"), @ColumnResult(name = "salary"),
						@ColumnResult(name = "emailId"), @ColumnResult(name = "status"),
						@ColumnResult(name = "cityName"), @ColumnResult(name = "companyName"),
						@ColumnResult(name = "desig"), @ColumnResult(name = "exp"),
						@ColumnResult(name = "mobileNo") }) }) })

@Entity
@Table(name = "employee", catalog = "sample", uniqueConstraints = { @UniqueConstraint(columnNames = "emailId"),
		@UniqueConstraint(columnNames = "mobileNo"), @UniqueConstraint(columnNames = "empName") })
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4458325470775410888L;
	private Integer id;
	private String firstName;
	private String lastName;
	private String empName;
	private String emailId;
	private Company Company;
	private String gender;
	private Date dob;
	private Boolean age;
	private String mobileNo;
	private String address;
	private City City;
	private String country;
	private String pincode;
	private Double salary;
	private Date joinDate;
	private String desig;
	private int exp;
	private Boolean status;
	private String cityName;
	private String companyName;

	public Employee() {
	}

	public Employee(String empName, String emailId) {
		this.empName = empName;
		this.emailId = emailId;
	}

	public Employee(String firstName, String lastName, String empName, String emailId, Company Company,
			String gender, Date dob, Boolean age, String mobileNo, String address, City City, String country,
			String pincode, double salary, Date joinDate, String desig, int exp, Boolean status) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.empName = empName;
		this.emailId = emailId;
		this.Company  = Company;
		this.gender = gender;
		this.dob = dob;
		this.age = age;
		this.mobileNo = mobileNo;
		this.address = address;
		this.City = City;
		this.country = country;
		this.pincode = pincode;
		this.salary = salary;
		this.joinDate = joinDate;
		this.desig = desig;
		this.exp = exp;
		this.status = status;
	}
	
	public Employee(City City, Company Company, String firstName, String empName, Date joinDate, double salary,
			String emailId, boolean status, String desig, int exp, String mobileNo) {
		this.City = City;
		this.Company = Company;
		this.firstName = firstName;
		this.empName = empName;
		this.joinDate = joinDate;
		this.salary = salary;
		this.emailId = emailId;
		this.status = status;
		this.desig = desig;
		this.exp = exp;
		this.mobileNo = mobileNo;
	}

	public Employee(int id, String firstName, String empName, Date joinDate, double salary, String emailId, boolean status,
			String cityName, String companyName, String desig, Integer exp, String mobileNo) {
		this.id = id;
		this.firstName = firstName;
		this.empName = empName;
		this.joinDate = joinDate;
		this.salary = salary;
		this.emailId = emailId;
		this.status = status;
		this.cityName = cityName;
		this.companyName = companyName;
		this.desig = desig;
		this.exp = exp;
		this.mobileNo = mobileNo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "empName", nullable = false, length = 45)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "emailId", nullable = false, length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "companyName", nullable = false)
	public Company getCompany() {
		return this.Company;
	}

	public void setCompany(Company Company) {
		this.Company = Company;
	}
	
	@Column(name = "gender", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "age")
	public Boolean getAge() {
		return this.age;
	}

	public void setAge(Boolean age) {
		this.age = age;
	}

	@Column(name = "mobileNo", length = 45)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "address", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cityName", nullable = false)
	public City getcity() {
		return this.City;
	}

	public void setCity(City City) {
		this.City = City;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "pincode", length = 45)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "salary", length = 45)
	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "joinDate", length = 10)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Column(name = "desig", length = 45)
	public String getDesig() {
		return this.desig;
	}

	public void setDesig(String desig) {
		this.desig = desig;
	}

	@Column(name = "exp", length = 45)
	public int getExp() {
		return this.exp;
	}

	public void setExp(int exp) {
		this.exp = exp;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}
	
	@Transient
	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Transient
	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}
}
