package org.sample.com.model;
// Generated Mar 19, 2018 3:20:26 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */

public class EmployeeDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String firstName;
	private String empName;
	private Date joinDate;
	private double salary;
	private String emailId;
	private int status;
	private String desig;
	private int exp;
	private String companyName;
	private String cityName;
	private String mobileNo;

	public EmployeeDetails() {
	}

	public EmployeeDetails(int id, String firstName, String empName, Date joinDate, double salary, String emailId,
			int status, String cityName, String companyName, String desig, int exp, String mobileNo) {
		this.id = id;
		this.firstName = firstName;
		this.empName = empName;
		this.joinDate = joinDate;
		this.salary = salary;
		this.emailId = emailId;
		this.status = status;
		this.cityName = cityName;
		this.companyName = companyName;
		this.desig = desig;
		this.exp = exp;
		this.mobileNo = mobileNo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Temporal(TemporalType.DATE)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getDesig() {
		return this.desig;
	}

	public void setDesig(String desig) {
		this.desig = desig;
	}

	public int getExp() {
		return this.exp;
	}

	public void setExp(int exp) {
		this.exp = exp;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

}
